### ISSUE TITLE
addAddonsToPackage throwing error of needing config

### ISSUE THREAD

**Issue by GCheung55** [runspired/flexi#66]
I'm installing 'flexi' via another addon. Looks like the config isn't copied over when installed via addon `addAddonsToPackage` or `addAddonToPackage` methods.

The error:

`You must define a config file for flexi at '/Users/gcheung/dev/fitbit/fitbit-ember-proto/config/flexi.js'`

**Comment by GCheung55** [comment]
Stacktrace:

```javascript
Error: You must define a config file for flexi at '/Users/gcheung/dev/fitbit/fitbit-ember-proto/config/flexi.js'
    at Class.module.exports.flexiConfig (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/flexi/index.js:74:17)
    at Class.module.exports.setupPreprocessorRegistry (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/flexi/index.js:89:54)
    at Object.module.exports.setupRegistry (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/ember-cli-preprocess-registry/preprocessors.js:44:16)
    at Class.Addon (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/ember-cli/lib/models/addon.js:109:5)
    at new Class (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/core-object/core-object.js:16:17)
    at /Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/ember-cli/lib/models/addons-factory.js:48:19
    at visit (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
    at Project.initializeAddons (/Users/gcheung/dev/fitbit/fitbit-ember-proto/node_modules/ember-cli/lib/models/project.js:374:36)
```

**Comment by GCheung55** [comment]
Stacktrace:

```javascript
Error: You must define a config file for flexi at '/dev/ember-proto/config/flexi.js'
    at Class.module.exports.flexiConfig (/dev/ember-proto/node_modules/flexi/index.js:74:17)
    at Class.module.exports.setupPreprocessorRegistry (/dev/ember-proto/node_modules/flexi/index.js:89:54)
    at Object.module.exports.setupRegistry (/dev/ember-proto/node_modules/ember-cli-preprocess-registry/preprocessors.js:44:16)
    at Class.Addon (/dev/ember-proto/node_modules/ember-cli/lib/models/addon.js:109:5)
    at new Class (/dev/ember-proto/node_modules/core-object/core-object.js:16:17)
    at /dev/ember-proto/node_modules/ember-cli/lib/models/addons-factory.js:48:19
    at visit (/dev/ember-proto/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/dev/ember-proto/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/dev/ember-proto/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
    at Project.initializeAddons (/dev/ember-proto/node_modules/ember-cli/lib/models/project.js:374:36)
```

**Comment by GCheung55** [comment]
What triggers `Project.initializeAddons` is https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/addon-install.js#L42
