### ISSUE TITLE
Support passing computeds in for properties

### ISSUE THREAD

**Issue by rwwagner90** [runspired/flexi#76]
Trying to do something like this fails:

`<centered md="{{foo}}"></centered>`

Shouldn't we be able to pass values in from the controller/component rather than always having to manually use a string like `"12"`?

**Comment by rwwagner90** [comment]
Just kidding, this works

**Comment by rwwagner90** [comment]
Just kidding again, it is an issue.

```js
foo: computed(function(){
    return '10';
  }),
```

and

```hbs
<centered md="{{foo}}"></centered>
```

Give an error on initial starting of the app:

```
TypeError: Cannot read property 'split' of undefined
    at /Users/wagner5/littlt1/sa-ui/sa/node_modules/flexi/dsl/attribute-conversion.js:128:39
    at Array.forEach (native)
    at /Users/wagner5/littlt1/sa-ui/sa/node_modules/flexi/dsl/attribute-conversion.js:124:24
    at Walker.visit (/Users/wagner5/littlt1/sa-ui/sa/bower_components/ember/ember-template-compiler.js:18742:7)
    at visitors.Program (/Users/wagner5/littlt1/sa-ui/sa/bower_components/ember/ember-template-compiler.js:18752:16)
    at Walker.children (/Users/wagner5/littlt1/sa-ui/sa/bower_components/ember/ember-template-compiler.js:18775:7)
    at Walker.visit (/Users/wagner5/littlt1/sa-ui/sa/bower_components/ember/ember-template-compiler.js:18743:12)
    at AttributeConversionSupport_transform [as transform] (/Users/wagner5/littlt1/sa-ui/sa/node_modules/flexi/dsl/attribute-conversion.js:96:10)
    at Object.preprocess (/Users/wagner5/littlt1/sa-ui/sa/bower_components/ember/ember-template-compiler.js:18024:27)
    at compileSpec (/Users/wagner5/littlt1/sa-ui/sa/bower_components/ember/ember-template-compiler.js:12943:37)
```

The weird thing is, if I change it to just `foo: '10'` and restart the app, then change it back to a computed, without restarting the server, it live reloads and allows me to use the computed without errors.

**Comment by rwwagner90** [comment]
Possible race condition? Seems unreliable to reproduce.

**Comment by runspired** [comment]
@rwwagner90 it's a template cache invalidation issue which I think will get properly cleaned up soon.  In regards to dynamic values, these are indeed unsupported as Flexi is a build time optimizer.
