### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by villander** [runspired/flexi#80]
I did this https://runspired.github.io/flexi/#/docs/installation

but not working for me. I have just the error: 

```
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: /addon.sass
in any of the following include paths:
  /Users/flama/Projects/remoto-app/tmp/sass_compiler-input_base_path-kMfsRlsS.tmp/0
    at Object.findFileSync (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/include-path-searcher/index.js:12:9)
    at SassCompiler.build (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:63:31)
    at /Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:149:21
    at lib$rsvp$$internal$$tryCatch (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

The broccoli plugin was instantiated at: 
    at SassCompiler.Plugin (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at SassCompiler.CachingWriter [as constructor] (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/index.js:27:12
    at Array.map (native)
    at SASSPlugin.toTree (/Users/flama/Projects/remoto-app/node_modules/ember-cli-sass/index.js:24:34)
    at /Users/flama/Projects/remoto-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/flama/Projects/remoto-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/Users/flama/Projects/remoto-app/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
```

**Comment by villander** [comment]
I'm using `ember-cli-sass` in my app as: 

```js
var app = new EmberApp(defaults, {
    sassOptions: {
      extension: 'sass'
    },
```

**Comment by villander** [comment]
@runspired

**Comment by villander** [comment]
Solved 🎉
